### ISSUE TITLE
Autolaunch Settings

### ISSUE THREAD

**Issue by testuser7** [reisxd/TizenBrew#20]
What is the difference between `Autolaunch Settings (module)` and `Autolaunch Settings for services` settings?
In both settings I see `TizenTube` as a choice.

If I set autostart then sometimes I get an error that the `@foxreis/tizentube` module was not found.

**Comment by reisxd** [comment]
The difference between autolaunch for modules and services is one for modules that have service files that you want to start up when TizenBrew starts up. The autolaunch for modules just automatically launchs the module you want (like TizenTube).

> If I set autostart then sometimes I get an error that the @foxreis/tizentube module was not found.

This happens when TizenBrew loads faster than modules could.

**Comment by testuser7** [comment]
> This happens when TizenBrew loads faster than modules could.

Can any changes improve this problem?
