### ISSUE TITLE
Issue on 2024 TV models

### ISSUE THREAD

**Issue by mattsouza26** [reisxd/TizenBrew#92]
I’m experiencing an issue with my 50Q60D TV and TizenBrew. After changing the HOST to 127.0.0.1, the app initially opens, but after a few seconds, it closes and doesn’t reopen. When I try to open it again, it closes immediately.

I tested this with the WGT file from the RELEASE page (resigned with my CERT) and also by compiling the source code myself. Both methods result in the same behavior.

**Comment by reisxd** [comment]
Try rebooting your TV first.

**Comment by mattsouza26** [comment]
> Try rebooting your TV first.
i did that, first i did install my compiled version, after change to 127.0.0.1 i restart the TV, and open the app, he load like 10 secs the app closes, and after that the app didnt open anymore, he open and closes like 1 secs, and they i did the same with the WGT compiled from GIT just ressign the CERT, and have the same result

**Comment by mattsouza26** [comment]
i don't know what was the issue, but seems to be fix after let the TV off for hours.

**Comment by susegg** [comment]
thx for the advise! - I thought I had messed up resigning the file, but I guess newer smart TVs might work similarly to Windows fast boot, where not everything is fully powered down.

Since I didn’t want to wait too long, I simply unplugged the TV for a few seconds, and it seemed to work!
If that's the case, it might be helpful to add this to the guide as well.
